# Generated by Django 4.1.7 on 2023-03-04 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("livro", "0004_categoria_usuario"),
    ]

    operations = [
        migrations.RemoveField(model_name="livros", name="data_devolucao",),
        migrations.RemoveField(model_name="livros", name="data_emprestimo",),
        migrations.RemoveField(model_name="livros", name="nome_emprestado",),
        migrations.RemoveField(model_name="livros", name="tempo_duracao",),
        migrations.CreateModel(
            name="Emprestimos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_emprestado", models.CharField(blank=True, max_length=30)),
                ("data_emprestimo", models.DateTimeField(blank=True, null=True)),
                ("data_devolucao", models.DateTimeField(blank=True, null=True)),
                ("tempo_duracao", models.DateField(blank=True, null=True)),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="livro.livros",
                    ),
                ),
            ],
        ),
    ]
