# Generated by Django 4.1.7 on 2023-03-04 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_usuario_ativo"),
        ("livro", "0005_remove_livros_data_devolucao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprestimos",
            name="nome_emprestado_anonimo",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="emprestimos",
            name="nome_emprestado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="usuarios.usuario"
            ),
        ),
    ]
