# Generated by Django 4.1.7 on 2023-03-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0009_remove_emprestimos_tempo_duracao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimos',
            options={},
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='avaliacao',
            field=models.CharField(choices=[('P', 'Péssimo'), ('R', 'Ruim'), ('B', 'Bom'), ('O', 'Ótimo')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
